name: build-image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: build the docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2
        with:
          context: .
          file: ./Dockerfile
          tags: aveshadev/slicegw-edge:latest
          push: false
      - name: List images
        run: docker image ls  
